-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
INSERT INTO note_type(id, jsonb)
    VALUES ('150a8806-a99d-48a3-89c4-313927df8634','{
                                                        "id": "150a8806-a99d-48a3-89c4-313927df8634",
                                                        "name": "General note",
                                                        "metadata": {
                                                            "createdDate": "2021-10-28T06:31:31.720+00:00",
                                                            "updatedDate": "2021-10-28T06:31:31.720+00:00"
                                                        }
                                                    }'),
    ('1611aee1-5679-4899-80f9-498c864a32ce','{
                                                 "id": "1611aee1-5679-4899-80f9-498c864a32ce",
                                                 "name": "Important note",
                                                 "metadata": {
                                                     "createdDate": "2021-10-28T10:46:55.066+00:00",
                                                     "updatedDate": "2021-10-28T10:46:55.066+00:00",
                                                     "createdByUserId": "undefined",
                                                     "updatedByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                     "createdByUsername": "diku_admin"
                                                 }
                                             }');
INSERT INTO note_data(id, jsonb)
	VALUES ('0044021e-796f-48d3-b5d9-7879cf5689bd', '{
                                                         "id": "0044021e-796f-48d3-b5d9-7879cf5689bd",
                                                         "links": [
                                                             {
                                                                 "id": "123356-3412711",
                                                                 "type": "package"
                                                             },
                                                             {
                                                                 "id": "123356-4075724",
                                                                 "type": "package"
                                                             }
                                                         ],
                                                         "title": "Package to buy",
                                                         "domain": "eholdings",
                                                         "typeId": "1611aee1-5679-4899-80f9-498c864a32ce",
                                                         "content": "<em>But this package</em>",
                                                         "creator": {
                                                             "lastName": "ADMINISTRATOR",
                                                             "firstName": "DIKU"
                                                         },
                                                         "metadata": {
                                                             "createdDate": "2021-10-28T10:51:33.756",
                                                             "updatedDate": "2021-10-28T10:51:33.756+00",
                                                             "createdByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                             "updatedByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                             "createdByUsername": "diku_admin",
                                                             "updatedByUsername": "undefined"
                                                         }
                                                     }'),
	('1a32c23f-eaa9-4e2b-b539-6be7bb74f70a', '{
                                                  "id": "1a32c23f-eaa9-4e2b-b539-6be7bb74f70a",
                                                  "links": [
                                                      {
                                                          "id": "bec20636-fb68-41fd-84ea-2cf910673599",
                                                          "type": "user"
                                                      }
                                                  ],
                                                  "title": "User shoud be fired",
                                                  "domain": "users",
                                                  "typeId": "1611aee1-5679-4899-80f9-498c864a32ce",
                                                  "content": "<strong>FIRE HIM!</strong>",
                                                  "creator": {
                                                      "lastName": "ADMINISTRATOR",
                                                      "firstName": "DIKU"
                                                  },
                                                  "metadata": {
                                                      "createdDate": "2021-10-28T10:47:55.008+00:00",
                                                      "updatedDate": "2021-10-28T10:47:55.008+00:00",
                                                      "createdByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                      "updatedByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                      "createdByUsername": "diku_admin"
                                                  },
                                                  "popUpOnUser": false,
                                                  "popUpOnCheckOut": false
                                              }'),
	('2da63dd4-f618-4b9d-a40f-d7bcaac95e8c', '{
                                                  "id": "2da63dd4-f618-4b9d-a40f-d7bcaac95e8c",
                                                  "links": [
                                                      {
                                                          "id": "bec20636-fb68-41fd-84ea-2cf910673599",
                                                          "type": "user"
                                                      }
                                                  ],
                                                  "title": "User needs new laptop",
                                                  "domain": "users",
                                                  "typeId": "150a8806-a99d-48a3-89c4-313927df8634",
                                                  "content": "This user needs new laptop",
                                                  "creator": {
                                                      "lastName": "ADMINISTRATOR",
                                                      "firstName": "DIKU"
                                                  },
                                                  "metadata": {
                                                      "createdDate": "2021-10-28T10:48:50.811+00:00",
                                                      "updatedDate": "2021-10-28T10:48:50.811+00:00",
                                                      "createdByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                      "updatedByUserId": "6f30f62c-d3cf-5ace-840d-6229ed676c4e",
                                                      "createdByUsername": "diku_admin"
                                                  },
                                                  "popUpOnUser": false,
                                                  "popUpOnCheckOut": false
                                              }');
END;
