stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-notes:spitfire-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-9tp2k:spitfire-helmcharts-mod-notes
      version: 0.1.32
      answers:
        image.repository: docker.dev.folio.org/mod-notes
        image.tag: spitfire-latest
      name: mod-notes
      targetNamespace: spitfire
timeout: 60
notification: {}
