stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mod-notes:malc-test
      registry: 127.0.0.1:34159
timeout: 60
notification: {}
