stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-openjdk-8
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - runScriptConfig:
      image: docker:stable-dind
      shellScript: 'docker build -t --network=host mod-notes:rancher-test . '
timeout: 60
notification: {}
