# Module properties
folio:
  environment: ${ENV:folio}
  exchange:
    enabled: true
  tenant:
    validation:
      enabled: true
  logging:
    request:
      enabled: true
      level: basic
    exchange:
      enabled: true
      level: basic
  notes:
    cache:
      configs:
        users-by-id:
          initialCapacity: 20
          maximumSize: 100
          expireAfterWrite: 60
    types:
      defaults:
        name: General note
        limit: ${NOTES_TYPES_DEFAULTS_LIMIT:25}
    content:
      allowed:
        tags:
          - p
          - strong
          - em
          - a
          - u
          - ol
          - ul
          - li
          - h1
          - h2
          - h3
          - br
        attributes:
          all:
            - class
          a:
            - href
            - rel
            - target
    response:
      limit: ${MAX_RECORDS_COUNT:1000}
  kafka:
    topics:
      - name: notes.note
        numPartitions: ${KAFKA_NOTE_TOPIC_PARTITIONS:1}
        replicationFactor: ${KAFKA_NOTE_TOPIC_REPLICATION_FACTOR:}

# Spring properties
spring:
  application:
    name: mod-notes
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
    producer:
      client-id: mod-notes
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      acks: all
      retries: 3
      properties:
        max.block.ms: ${KAFKA_PRODUCER_MAX_BLOCK_MS:10000}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
  sql:
    init:
      continue-on-error: true
  datasource:
    password: ${DB_PASSWORD:folio_admin}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
    username: ${DB_USERNAME:folio_admin}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.xml
    enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  cache:
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace,loggers
      base-path: /admin
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
  endpoint:
    loggers:
      access: unrestricted
server:
  port: 8081

logging:
  level:
    org.folio.spring.filter.IncomingRequestLoggingFilter: DEBUG
