#%RAML 1.0

title: Notes API
baseUri: https://github.com/folio-org/mod-notes
version: v1

documentation:
  - title: mod-notes API
    content: This documents the API calls that can be made to query and manage notes about all kind of objects

types:
  note: !include note.json
  newnote: !include newnote.json
  entity: !include entity.json
  noteCollection: !include noteCollection.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/notes:
  displayName: Notes
  description: Notes collection
  type:
    collection:
      schemaCollection: noteCollection
      schemaItem: note
      exampleCollection: !include examples/noteCollection.sample
      exampleItem: !include examples/note.sample
  post:
    is: [ validate ]
  get:
    is: [
      searchable: {description: "with valid searchable fields: for example link = 1234", example: "link=/users/1234"},
      pageable,
      validate
    ]
    responses:
  /_self:
    displayName: Notes created by current user
    type:
      collection:
        schemaCollection: noteCollection
        schemaItem: note
        exampleCollection: !include examples/noteCollection.sample
        exampleItem: !include examples/note.sample
    get:
      is: [
        searchable: {description: "with valid searchable fields: for example link = 1234", example: "link=/users/1234"},
        pageable,
        validate
      ]
  /{id}:
    displayName: Notes
    description: Get, Delete or Update a specific note
    type:
      collection-item:
        schema: note
        exampleItem: !include examples/note.sample
    get:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    put:
      is: [validate]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
    delete:
      is: [ validate ]
      responses:
        400:
          description: "Bad request"
          body:
            text/plain:
        401:
          description: "Not authorized to perform requested action"
          body:
            text/plain:
