#%RAML 1.0
title: Note Types
version: v1.0.0
baseUri: http://github.com/org/folio/mod-notes

documentation:
  - title: mod-notes Type API
    content: This documents the API calls that can be made to query and manage note types of the system

types:
  noteTypeCollection: !include types/notetypes/noteTypeCollection.json
  noteType: !include types/notetypes/noteTypeItem.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/note-types:
  type:
    collection:
      exampleCollection: !include examples/notetypes/noteTypeCollection.sample
      exampleItem: !include examples/notetypes/noteTypeItem.sample
      schemaCollection: noteTypeCollection
      schemaItem: noteType
  get:
    is: [
      searchable: {description: "", example: "type=*high*"},
      pageable
    ]
    description: Return a list of note types
  post:
    is: [validate]
    description: Create a note type
  /{typeId}:
    uriParameters:
      typeId:
        pattern : "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
    type:
      collection-item:
        exampleItem: !include examples/notetypes/noteTypeItem.sample
        schema: noteType
